### PR TITLE
Updates for PureScript 0.9

### PR DESCRIPTION
**Pull request by sharkdp**
Unfortunately, I wasn't able to test this (because test-unit is not compatible with PS 0.9, yet). But with this change, it builds..

### CODE REVIEW

**Comment by bodil** [comment]
And these tests won't run on the latest version of test-unit anyway, Node's scheduler is apparently too imprecise to run them concurrently... I was leaving that as a future project.

**Comment by bodil** [comment]
I've published a new version, fyi, but it's not on Pursuit because psc-publish won't let me until the devDependencies work.

**Comment by sharkdp** [comment]
> I've published a new version, fyi, but it's not on Pursuit because psc-publish won't let me until the devDependencies work.

Thanks!

I believe Pursuit is not up to date with PureScript 0.9 anyway...

**Comment by bodil** [comment]
Yes, I found that out the hard way too after trying to publish smolder...

**Pull request merged**
